// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QazoniHisoblovchi.Infrastructure;

#nullable disable

namespace QazoniHisoblovchi.Infrastructure.Migrations
{
    [DbContext(typeof(QazoHisoblovchiDbContext))]
    partial class QazoHisoblovchiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QazoniHisoblovchi.Domain.Entities.Foydalanuvchilar", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Martaba")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("foydalanuvchilar");
                });

            modelBuilder.Entity("QazoniHisoblovchi.Domain.Entities.QazoNamozlar", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Asr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AsrSafar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bomdod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FoydalanuvchiId")
                        .HasColumnType("int");

                    b.Property<string>("Peshin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PeshinSafar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Roza")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Shom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vitr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Xufton")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XuftonSafar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("qazoNamozlar");
                });
#pragma warning restore 612, 618
        }
    }
}
